-- Data Skill Map - eventos de funil do Diagnostico 2.0
--
-- Execute este arquivo no SQL Editor do Supabase.
--
-- Objetivo:
-- - Preparar o banco para medir diagnosticos iniciados, abandonados e concluidos por etapa.
-- - Registrar eventos antes do resultado final, evitando depender apenas da sessao consolidada.
-- - Permitir analytics de funil sem alterar o frontend nesta etapa.
--
-- Observacao:
-- Esta migration apenas prepara a estrutura do banco. O frontend sera conectado
-- em uma etapa futura para enviar os eventos durante a jornada do Diagnostico 2.0.

-- 1) Tabela de eventos do funil do diagnostico.
create table if not exists public.diagnostic_funnel_events (
  id bigint generated by default as identity primary key,
  attempt_id text not null,
  anonymous_user_id text null,
  user_id uuid null references auth.users(id) on delete set null,
  event_type text not null,
  level text null,
  question_index integer null,
  total_questions_answered integer null,
  score_percent numeric null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint diagnostic_funnel_events_attempt_id_not_empty
    check (length(trim(attempt_id)) > 0),

  constraint diagnostic_funnel_events_anonymous_user_id_not_empty
    check (anonymous_user_id is null or length(trim(anonymous_user_id)) > 0),

  constraint diagnostic_funnel_events_event_type_check
    check (
      event_type in (
        'started',
        'completed_basic',
        'completed_intermediate',
        'completed_advanced',
        'generated_final_result',
        'continued_to_next_level',
        'abandoned_marker'
      )
    ),

  constraint diagnostic_funnel_events_level_check
    check (
      level is null
      or level in (
        'Básico',
        'Intermediário',
        'Avançado',
        'Final'
      )
    ),

  constraint diagnostic_funnel_events_question_index_check
    check (question_index is null or question_index >= 0),

  constraint diagnostic_funnel_events_total_questions_answered_check
    check (total_questions_answered is null or total_questions_answered >= 0),

  constraint diagnostic_funnel_events_score_percent_check
    check (score_percent is null or (score_percent >= 0 and score_percent <= 100))
);

comment on table public.diagnostic_funnel_events is
  'Eventos do funil do Diagnostico 2.0 para medir inicio, abandono, continuidade e conclusao por etapa.';

comment on column public.diagnostic_funnel_events.attempt_id is
  'Identificador da tentativa de diagnostico. Deve ser enviado desde o inicio da jornada.';

comment on column public.diagnostic_funnel_events.event_type is
  'Evento do funil: started, completed_basic, completed_intermediate, completed_advanced, generated_final_result, continued_to_next_level ou abandoned_marker.';

comment on column public.diagnostic_funnel_events.metadata is
  'Dados complementares do evento. Nao deve substituir os campos estruturados principais.';

-- 2) Indices para consulta por tentativa, usuario, evento e serie temporal.
create index if not exists idx_diagnostic_funnel_events_attempt_id
  on public.diagnostic_funnel_events (attempt_id);

create index if not exists idx_diagnostic_funnel_events_anonymous_user_id
  on public.diagnostic_funnel_events (anonymous_user_id);

create index if not exists idx_diagnostic_funnel_events_user_id
  on public.diagnostic_funnel_events (user_id);

create index if not exists idx_diagnostic_funnel_events_event_type
  on public.diagnostic_funnel_events (event_type);

create index if not exists idx_diagnostic_funnel_events_created_at
  on public.diagnostic_funnel_events (created_at);

create index if not exists idx_diagnostic_funnel_events_attempt_event_type
  on public.diagnostic_funnel_events (attempt_id, event_type);

create index if not exists idx_diagnostic_funnel_events_anonymous_created_at
  on public.diagnostic_funnel_events (anonymous_user_id, created_at);

-- 3) RLS: frontend pode inserir eventos, mas leitura direta fica restrita.
alter table public.diagnostic_funnel_events enable row level security;

drop policy if exists "anon_insert_diagnostic_funnel_events" on public.diagnostic_funnel_events;
create policy "anon_insert_diagnostic_funnel_events"
on public.diagnostic_funnel_events
for insert
to anon
with check (user_id is null);

drop policy if exists "authenticated_insert_own_diagnostic_funnel_events" on public.diagnostic_funnel_events;
create policy "authenticated_insert_own_diagnostic_funnel_events"
on public.diagnostic_funnel_events
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "authenticated_select_own_diagnostic_funnel_events" on public.diagnostic_funnel_events;
create policy "authenticated_select_own_diagnostic_funnel_events"
on public.diagnostic_funnel_events
for select
to authenticated
using (user_id = auth.uid());

-- 4) Grants minimos.
grant usage on schema public to anon, authenticated;

grant insert on table public.diagnostic_funnel_events to anon;
grant insert, select on table public.diagnostic_funnel_events to authenticated;

grant usage, select on sequence public.diagnostic_funnel_events_id_seq to anon, authenticated;

-- Defesa explicita: o frontend nao deve atualizar, remover ou listar eventos anonimos.
revoke select on table public.diagnostic_funnel_events from anon;
revoke update, delete on table public.diagnostic_funnel_events from anon, authenticated;

-- 5) View agregada para analytics interno.
-- A view nao expoe eventos individuais. Ainda assim, o acesso direto por anon/authenticated
-- fica revogado para manter o padrao de analytics interno seguro do projeto.
create or replace view public.vw_diagnostic_funnel_daily
with (security_invoker = true)
as
select
  date_trunc('day', created_at)::date as event_date,
  event_type,
  count(*)::bigint as total_events,
  count(distinct attempt_id)::bigint as total_attempts,
  count(distinct user_id)::bigint as authenticated_users,
  count(distinct anonymous_user_id)::bigint as anonymous_users,
  count(*) filter (where level = 'Básico')::bigint as basic_events,
  count(*) filter (where level = 'Intermediário')::bigint as intermediate_events,
  count(*) filter (where level = 'Avançado')::bigint as advanced_events,
  count(*) filter (where level = 'Final')::bigint as final_events,
  round(avg(score_percent), 2) as avg_score_percent
from public.diagnostic_funnel_events
group by date_trunc('day', created_at)::date, event_type;

comment on view public.vw_diagnostic_funnel_daily is
  'Agregado diario de eventos do funil do Diagnostico 2.0 para analytics interno.';

revoke all on public.vw_diagnostic_funnel_daily from anon, authenticated;
