-- Data Skill Map - Question Bank Reset v1
-- Este script define a base v1 como conjunto ativo oficial.
-- Qualquer pergunta fora de `diagnostico_v1_%` e `desafio_v1_%` será desativada.
-- Não apaga histórico, não usa DELETE e não recria tabelas.

begin;

-- Auditoria de duplicidade (ignora question_key nulo)
select question_key, count(*) as total
from public.question_bank
where question_key is not null
group by question_key
having count(*) > 1;

do $$
begin
  if exists (
    select 1
    from public.question_bank
    where question_key is not null
    group by question_key
    having count(*) > 1
  ) then
    raise exception 'Existem question_key duplicadas em public.question_bank. Corrija antes de continuar.';
  end if;
end $$;

create unique index if not exists question_bank_question_key_uidx
on public.question_bank (question_key);

update public.question_bank
set is_active = false,
    updated_at = now()
where coalesce(question_key, '') not like 'diagnostico_v1_%'
  and coalesce(question_key, '') not like 'desafio_v1_%';

insert into public.question_bank (
  question_key,
  mode,
  area,
  category,
  level,
  concept,
  question,
  code,
  context,
  options,
  correct_index,
  explanation,
  points,
  is_active,
  display_order,
  source,
  difficulty_score,
  question_type,
  tags,
  estimated_time_seconds
)
values
  ('diagnostico_v1_001', 'diagnostico', 'SQL', 'SQL', 'Básico', 'Filtro de período', 'Você recebeu um pedido para mostrar apenas as vendas dos últimos 30 dias. Qual abordagem SQL atende melhor ao pedido?', '', 'Tabela vendas possui data_venda e valor.', '["Aplicar WHERE data_venda >= data atual menos 30 dias","Ordenar por data_venda descendente","Usar GROUP BY data_venda","Usar DISTINCT em data_venda"]'::jsonb, 0, 'Para limitar linhas por período, o filtro deve estar no WHERE.', null, true, 1, 'question_bank_reset_v1', 2, 'cenario', array['sql','where','filtro_data'], 60),
  ('diagnostico_v1_002', 'diagnostico', 'SQL', 'SQL', 'Básico', 'Contagem com nulos', 'Em um relatório de contatos, a coluna email tem campos vazios. Qual contagem retorna apenas registros com email preenchido?', '', 'Tabela clientes possui id_cliente e email.', '["COUNT(*)","COUNT(email)","COUNT(DISTINCT email)","COUNT(1)"]'::jsonb, 1, 'COUNT(coluna) ignora valores nulos e conta somente os preenchidos.', null, true, 2, 'question_bank_reset_v1', 2, 'conceitual', array['sql','count','null'], 45),
  ('diagnostico_v1_003', 'diagnostico', 'SQL', 'SQL', 'Básico', 'Ordenação final', 'Você precisa listar produtos do maior para o menor preço no resultado final. Qual cláusula deve ser usada?', '', 'Tabela produtos possui nome e preço.', '["GROUP BY preço DESC","WHERE preço DESC","ORDER BY preço DESC","HAVING preço DESC"]'::jsonb, 2, 'ORDER BY define a ordenação final das linhas retornadas.', null, true, 3, 'question_bank_reset_v1', 1, 'conceitual', array['sql','order_by'], 45),
  ('diagnostico_v1_004', 'diagnostico', 'SQL', 'SQL', 'Básico', 'Filtro antes de agregação', 'Ao calcular faturamento por loja, você quer excluir cancelamentos antes da SOMA. Onde esse filtro deve entrar?', '', 'Tabela vendas possui loja_id, status e valor.', '["No WHERE antes do GROUP BY","No ORDER BY","Em uma view sem filtro","No alias da coluna de SOMA"]'::jsonb, 0, 'Filtros de linha antes da agregação devem ser aplicados no WHERE.', null, true, 4, 'question_bank_reset_v1', 2, 'cenario', array['sql','where','group_by'], 60),
  ('diagnostico_v1_005', 'diagnostico', 'SQL', 'SQL', 'Básico', 'JOIN básico', 'Você precisa mostrar nome do cliente e data da compra. Qual operação combina dados de duas tabelas por chave?', '', 'Tabelas clientes e compras compartilham id_cliente.', '["JOIN por id_cliente","ORDER BY em ambas","DISTINCT em compras","LIMIT em clientes"]'::jsonb, 0, 'JOIN relaciona registros de tabelas diferentes com base em uma chave comum.', null, true, 5, 'question_bank_reset_v1', 2, 'conceitual', array['sql','join','chave'], 60),
  ('diagnostico_v1_006', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'LEFT JOIN e cobertura', 'A equipe quer uma lista de todos os clientes, inclusive os sem pedidos. Qual estratégia evita perder esses clientes?', '', 'Clientes pode não ter correspondência em pedidos.', '["INNER JOIN clientes-pedidos","LEFT JOIN clientes para pedidos","RIGHT JOIN pedidos para clientes","UNION sem chave"]'::jsonb, 1, 'LEFT JOIN preserva a tabela da esquerda e mostra nulos quando não há pedido.', null, true, 6, 'question_bank_reset_v1', 3, 'cenario', array['sql','left_join','cobertura'], 75),
  ('diagnostico_v1_007', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'Duplicidade em agregação', 'Depois de juntar pedidos e itens, a receita total ficou maior que o esperado. Qual verificação é mais importante primeiro?', '', 'Receita foi somada após JOIN.', '["Checar cardinalidade do JOIN e granularidade","Trocar SUM por COUNT para reduzir duplicidade","Ordenar por valor total por pedido","Aplicar DISTINCT na consulta inteira sem revisar a junção"]'::jsonb, 0, 'Inflação da SOMA costuma ser problema de cardinalidade ou granularidade do relacionamento.', null, true, 7, 'question_bank_reset_v1', 3, 'interpretacao', array['sql','join','granularidade'], 90),
  ('diagnostico_v1_008', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'DISTINCT em entidade', 'Uma tabela possui uma linha por item vendido. Como contar pedidos únicos no período?', '', 'Tabela itens_venda possui pedido_id repetido.', '["COUNT(*)","COUNT(pedido_id)","COUNT(DISTINCT pedido_id)","COUNT(DISTINCT cliente_id)"]'::jsonb, 2, 'COUNT(DISTINCT) remove repetições da chave e retorna entidades únicas.', null, true, 8, 'question_bank_reset_v1', 3, 'cenario', array['sql','distinct','contagem'], 60),
  ('diagnostico_v1_009', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'HAVING versus WHERE', 'Você quer listar somente lojas com faturamento acima de 100 mil no mês. Qual cláusula filtra corretamente o resultado agregado?', '', 'A consulta agrupa por loja e SOMA valor.', '["WHERE SUM(valor) > 100000","HAVING SUM(valor) > 100000","ORDER BY SUM(valor) > 100000","LIMIT 100000"]'::jsonb, 1, 'HAVING filtra grupos após a agregação.', null, true, 9, 'question_bank_reset_v1', 3, 'conceitual', array['sql','having','agregacao'], 75),
  ('diagnostico_v1_010', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'CTE para legibilidade', 'Um analista separou uma consulta longa em duas etapas com WITH. Qual benefício principal dessa escolha?', '', 'Consulta envolve limpeza e agregação em etapas.', '["Evitar qualquer JOIN","Substituir índice de banco","Melhorar legibilidade e manutenção","Garantir sempre menor custo"]'::jsonb, 2, 'CTE organiza passos lógicos e facilita leitura e manutenção.', null, true, 10, 'question_bank_reset_v1', 3, 'conceitual', array['sql','cte','manutencao'], 60),
  ('diagnostico_v1_011', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'Janela de ranking', 'Você precisa marcar o maior pedido de cada cliente sem perder detalhes das linhas. Qual recurso é mais adequado?', '', 'Tabela pedidos possui cliente_id e valor.', '["GROUP BY cliente_id","ROW_NUMBER() OVER(PARTITION BY cliente_id ORDER BY valor DESC)","DISTINCT cliente_id","HAVING valor = MAX(valor)"]'::jsonb, 1, 'Funções de janela calculam ranking mantendo a granularidade original.', null, true, 11, 'question_bank_reset_v1', 4, 'codigo', array['sql','window_function','ranking'], 90),
  ('diagnostico_v1_012', 'diagnostico', 'SQL', 'SQL', 'Intermediário', 'Subconsulta correlacionada', 'Para cada produto, você quer comparar o preço atual com a MÉDIA da própria categoria. Qual abordagem funciona?', '', 'Produtos possuem categoria e preço.', '["Comparar com MÉDIA global de todos produtos","Usar subconsulta por categoria do produto","Ordenar por categoria","Usar LIMIT 1"]'::jsonb, 1, 'A comparação correta exige MÉDIA calculada na mesma categoria do item.', null, true, 12, 'question_bank_reset_v1', 4, 'cenario', array['sql','subconsulta','categoria'], 90),
  ('diagnostico_v1_013', 'diagnostico', 'SQL', 'SQL', 'Avançado', 'Churn com coorte', 'Você precisa medir churn mensal por coorte de entrada. Qual estrutura ajuda a manter consistência entre meses?', '', 'Base tem data_primeira_compra e data_ultima_compra.', '["Agrupar apenas por mês corrente","Definir coorte fixa de entrada e acompanhar retenção por período","Usar somente total acumulado anual","Filtrar apenas clientes ativos"]'::jsonb, 1, 'Análise de coorte compara grupos equivalentes ao longo do tempo.', null, true, 13, 'question_bank_reset_v1', 5, 'negocio', array['sql','coorte','churn'], 90),
  ('diagnostico_v1_014', 'diagnostico', 'SQL', 'SQL', 'Avançado', 'SCD e histórico', 'Um dashboard de receita por gerente mudou após troca de carteira. Qual estratégia evita reescrever histórico indevidamente?', '', 'Dimensão de gerente possui vigência temporal.', '["Atualizar todos registros antigos com gerente atual","Ignorar data de vigência da dimensão","Usar relacionamento por chave e intervalo de vigência","Somar apenas mês atual"]'::jsonb, 2, 'Dimensões com vigência preservam o contexto histórico correto.', null, true, 14, 'question_bank_reset_v1', 5, 'cenario', array['sql','scd','historico'], 90),
  ('diagnostico_v1_015', 'diagnostico', 'SQL', 'SQL', 'Avançado', 'Qualidade de dados em pipeline', 'A mesma venda aparece duplicada em cargas diferentes. Qual critério reduz duplicidade com rastreabilidade?', '', 'Existe chave de negócio e timestamp de atualização.', '["Remover linhas aleatoriamente","Aplicar deduplicação por chave de negócio e manter mais recente","Excluir todas as cargas antigas","Agrupar por valor total"]'::jsonb, 1, 'Deduplicacao por chave e regra temporal preserva consistência e auditoria.', null, true, 15, 'question_bank_reset_v1', 4, 'interpretacao', array['sql','deduplicacao','pipeline'], 90),
  ('diagnostico_v1_016', 'diagnostico', 'SQL', 'SQL', 'Avançado', 'Desempenho de consulta', 'Uma consulta analítica com filtros frequentes em data e loja ficou lenta. Qual ação costuma trazer ganho sem mudar regra de negócio?', '', 'Tabela fato com alto volume.', '["Criar índice alinhado aos filtros principais","Remover filtros de negócio","Trocar SUM por COUNT","Executar sempre de madrugada"]'::jsonb, 0, 'índice coerente com predicados frequentes tende a reduzir custo de leitura.', null, true, 16, 'question_bank_reset_v1', 4, 'negocio', array['sql','performance','indice'], 75),
  ('diagnostico_v1_017', 'diagnostico', 'Excel', 'Excel', 'Básico', 'Referência absoluta', 'Você precisa copiar uma fórmula de meta fixa para várias linhas. Qual referência deve ficar travada?', '', 'Planilha possui meta na célula B1.', '["B1","$B$1","B$1 e $B1 sempre equivalentes","Nenhuma referência pode travar"]'::jsonb, 1, 'A referência absoluta fixa linha e coluna ao copiar fórmula.', null, true, 17, 'question_bank_reset_v1', 1, 'conceitual', array['excel','referencia_absoluta'], 45),
  ('diagnostico_v1_018', 'diagnostico', 'Excel', 'Excel', 'Básico', 'Busca por código', 'Você quer trazer a descrição do produto a partir do código em outra aba. Qual função é mais indicada?', '', 'Tabela de apoio contém código e descrição.', '["SOMA","SE","PROCV ou PROCX","MÉDIA"]'::jsonb, 2, 'Funções de busca retornam valores associados a uma chave.', null, true, 18, 'question_bank_reset_v1', 2, 'cenario', array['excel','procv','procx'], 60),
  ('diagnostico_v1_019', 'diagnostico', 'Excel', 'Excel', 'Básico', 'Filtro em tabela', 'Para analisar somente pedidos cancelados em uma lista grande, qual recurso atende melhor?', '', 'Base de pedidos em formato tabular.', '["Filtro de coluna","Congelar painéis","Quebra de página","Mesclar células"]'::jsonb, 0, 'Filtro permite restringir visualização sem alterar dados originais.', null, true, 19, 'question_bank_reset_v1', 1, 'conceitual', array['excel','filtro','tabela'], 45),
  ('diagnostico_v1_020', 'diagnostico', 'Excel', 'Excel', 'Básico', 'Soma condicional', 'Você precisa somar vendas apenas do canal online. Qual função resolve de forma direta?', '', 'Coluna canal e coluna valor na mesma tabela.', '["SOMA","SOMASE","CONT.SE","PROCV"]'::jsonb, 1, 'SOMASE SOMA apenas linhas que atendem ao critério informado.', null, true, 20, 'question_bank_reset_v1', 2, 'cenario', array['excel','somase','criterio'], 60),
  ('diagnostico_v1_021', 'diagnostico', 'Excel', 'Excel', 'Básico', 'Tipo de dado', 'Uma coluna de datas veio como texto e o gráfico mensal falhou. Qual ação inicial e mais adequada?', '', 'Datas estão no formato texto.', '["Converter a coluna para tipo data e validar locale","Aplicar apenas formato visual de data sem converter o tipo","Criar coluna auxiliar de mês e ano sem corrigir a origem","Substituir separadores de data sem testar consistência"]'::jsonb, 0, 'Gráficos e funções de período dependem de tipo data válido.', null, true, 21, 'question_bank_reset_v1', 2, 'interpretacao', array['excel','tipo_dado','datas'], 60),
  ('diagnostico_v1_022', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Tabela dinâmica', 'Você quer receita por mês nas linhas e por categoria nas colunas. Qual configuração é correta?', '', 'Campo receita deve ser agregado.', '["Linhas: mês; Colunas: categoria; Valores: SOMA da receita","Linhas: receita; Colunas: mês; Valores: categoria","Linhas: categoria; Valores: texto","Colunas: receita; Valores: mês"]'::jsonb, 0, 'Tabela dinâmica separa dimensões em linhas e colunas e mede no campo valores.', null, true, 22, 'question_bank_reset_v1', 3, 'cenario', array['excel','tabela_dinamica','agregacao'], 75),
  ('diagnostico_v1_023', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Validação de dados', 'Usuários digitam status fora do padrão e quebram os indicadores. Qual controle reduz esse problema na origem?', '', 'Status esperado: Aberto, Fechado, Em análise.', '["Formatação condicional","Validação de dados com lista permitida","Classificação por cor","Mesclar células de status"]'::jsonb, 1, 'Validação com lista restringe entradas e melhora consistência da base.', null, true, 23, 'question_bank_reset_v1', 3, 'negocio', array['excel','qualidade_dados','validacao'], 75),
  ('diagnostico_v1_024', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Erro de procura', 'Um PROCX retorna erro para alguns códigos que existem. Qual investigação costuma ser mais útil primeiro?', '', 'Código pode ter espaços extras.', '["Conferir se há espaços e tipos diferentes na chave","Trocar para SOMA","Reordenar a planilha","Apagar linhas com erro"]'::jsonb, 0, 'Inconsistência de tipo ou espaço na chave é causa frequente de falha de busca.', null, true, 24, 'question_bank_reset_v1', 3, 'interpretacao', array['excel','procx','chave'], 75),
  ('diagnostico_v1_025', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Intervalo dinâmico', 'Seu dashboard mensal precisa incorporar novas linhas automaticamente. Qual prática ajuda mais?', '', 'Novos dados são adicionados toda semana.', '["Converter base em Tabela do Excel","Fixar intervalo manual para sempre","Usar apenas copiar e colar","Travar cálculo automático"]'::jsonb, 0, 'Tabela estruturada expande fórmulas e referência automaticamente com novas linhas.', null, true, 25, 'question_bank_reset_v1', 3, 'cenario', array['excel','tabela_estruturada','dashboard'], 60),
  ('diagnostico_v1_026', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Auditoria de fórmula', 'Dois analistas chegam em resultados diferentes para o mesmo KPI. Qual passo ajuda a identificar a divergência?', '', 'Cada um usa sua própria planilha.', '["Rastrear precedentes e dependentes da fórmula","Comparar com versão anterior da planilha sem rastrear fórmulas","Aplicar cálculo manual em uma aba de teste","Recalcular somente células com resultado fora da meta"]'::jsonb, 0, 'Auditoria de fórmula mostra de onde os cálculos estão puxando valores.', null, true, 26, 'question_bank_reset_v1', 3, 'interpretacao', array['excel','auditoria','formula'], 75),
  ('diagnostico_v1_027', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Segmentação por período', 'Você precisa comparar desempenho antes e depois de uma campanha por semanas. Qual recurso agiliza essa leitura?', '', 'Base possui data e vendas.', '["Segmentação de dados conectada a tabela dinâmica","Mesclar todas as semanas","Ocultar colunas alternadas","Usar apenas barra de rolagem"]'::jsonb, 0, 'Segmentadores permitem cortes rápidos e consistentes sobre a mesma base agregada.', null, true, 27, 'question_bank_reset_v1', 3, 'cenario', array['excel','segmentacao','analise_tempo'], 60),
  ('diagnostico_v1_028', 'diagnostico', 'Excel', 'Excel', 'Intermediário', 'Tratamento de duplicados', 'Uma exportação traz pedidos repetidos e infla a SOMA de receita. Qual ação inicial e mais segura?', '', 'Existe id_pedido único esperado.', '["Remover duplicados com base no id_pedido","Excluir metade das linhas","Somar por valor sem chave","Ajustar apenas o gráfico"]'::jsonb, 0, 'A regra de deduplicação deve usar chave de negócio confiável.', null, true, 28, 'question_bank_reset_v1', 4, 'negocio', array['excel','deduplicacao','id_pedido'], 75),
  ('diagnostico_v1_029', 'diagnostico', 'Excel', 'Excel', 'Avançado', 'Power Query e ETL', 'Dados chegam de três arquivos com colunas inconsistentes todo dia. Qual abordagem reduz retrabalho manual?', '', 'Arquivos CSV diários com mesmo tema.', '["Power Query com etapas de transformação salvas","Copiar e colar manualmente com checklist","Padronizar cabeçalhos com fórmulas sem pipeline de carga","Usar apenas filtro visual na planilha final"]'::jsonb, 0, 'Power Query permite padronizar e repetir transformações com menor erro operacional.', null, true, 29, 'question_bank_reset_v1', 4, 'cenario', array['excel','power_query','etl'], 90),
  ('diagnostico_v1_030', 'diagnostico', 'Excel', 'Excel', 'Avançado', 'Modelo de dados', 'Seu arquivo usa várias tabelas conectadas por chaves. Qual benefício principal do Modelo de Dados?', '', 'Relacionamentos entre vendas, produtos e clientes.', '["Facilitar análises sem duplicar colunas em uma tabela única","Eliminar necessidade de qualquer chave","Substituir toda validação de dados","Garantir sempre cálculo mais rápido"]'::jsonb, 0, 'Modelo relacional reduz redundância e melhora a consistência analítica.', null, true, 30, 'question_bank_reset_v1', 4, 'conceitual', array['excel','modelo_dados','relacionamento'], 90),
  ('diagnostico_v1_031', 'diagnostico', 'Excel', 'Excel', 'Avançado', 'Medidas e contexto', 'Uma medida de margem muda quando você altera o filtro de categoria. Isso indica qual conceito central?', '', 'Dashboard com medidas no modelo.', '["Contexto de filtro influência resultado da medida","Erro automático na planilha","Medida não pode usar filtro","Categoria sempre deve ser fixa"]'::jsonb, 0, 'Medidas são avaliadas no contexto de filtro ativo.', null, true, 31, 'question_bank_reset_v1', 5, 'interpretacao', array['excel','medidas','contexto_filtro'], 90),
  ('diagnostico_v1_032', 'diagnostico', 'Excel', 'Excel', 'Avançado', 'Governança de planilha', 'Seu time compartilha uma planilha crítica com dezenas de editores. Qual prática reduz risco de quebra de fórmula?', '', 'Uso colaborativo intenso.', '["Separar abas de entrada e cálculo com proteção de células","Permitir edição total sem controle","Remover histórico de versão","Ocultar erros com formato"]'::jsonb, 0, 'Segregação de entrada e cálculo com proteção aumenta confiabilidade operacional.', null, true, 32, 'question_bank_reset_v1', 4, 'negocio', array['excel','governanca','protecao'], 75),
  ('diagnostico_v1_033', 'diagnostico', 'Estatística', 'Estatística', 'Básico', 'Mediana e outlier', 'Um conjunto tem alguns valores extremos muito altos. Qual medida tende a representar melhor o centro nesse caso?', '', 'Distribuição assimétrica com outliers.', '["Média","Mediana","Soma","Amplitude"]'::jsonb, 1, 'Mediana e menos sensível a extremos do que a MÉDIA.', null, true, 33, 'question_bank_reset_v1', 1, 'conceitual', array['estatistica','mediana','outlier'], 45),
  ('diagnostico_v1_034', 'diagnostico', 'Estatística', 'Estatística', 'Básico', 'Percentual simples', 'A meta era 200 e o realizado foi 150. Qual percentual de atingimento foi obtido?', '', 'Cálculo básico de atingimento.', '["75%","50%","125%","25%"]'::jsonb, 0, 'Atingimento = realizado dividido pela meta: 150/200 = 75%.', null, true, 34, 'question_bank_reset_v1', 1, 'conceitual', array['estatistica','percentual','meta'], 45),
  ('diagnostico_v1_035', 'diagnostico', 'Estatística', 'Estatística', 'Básico', 'Leitura de variação', 'A taxa subiu de 20% para 25%. Qual interpretação está correta?', '', 'Comparação entre dois períodos.', '["Aumento de 5 pontos percentuais","Aumento de 25 pontos percentuais","Queda de 5 pontos percentuais","Sem variação"]'::jsonb, 0, 'A diferença absoluta entre taxas e medida em pontos percentuais.', null, true, 35, 'question_bank_reset_v1', 2, 'interpretacao', array['estatistica','pontos_percentuais'], 60),
  ('diagnostico_v1_036', 'diagnostico', 'Estatística', 'Estatística', 'Básico', 'Amostra e população', 'Seu time avaliou 300 clientes de um universo de 20 mil. Esse conjunto de 300 é chamado de?', '', 'Pesquisa por amostragem.', '["População total","Amostra","Outlier","Série temporal"]'::jsonb, 1, 'Amostra é o subconjunto observado para inferir sobre a população.', null, true, 36, 'question_bank_reset_v1', 1, 'conceitual', array['estatistica','amostragem'], 45),
  ('diagnostico_v1_037', 'diagnostico', 'Estatística', 'Estatística', 'Básico', 'Dispersão', 'Duas equipes tem MÉDIA de vendas igual, mas uma oscila muito mais. Qual medida ajuda a comparar essa variabilidade?', '', 'Comparação de estabilidade.', '["Desvio padrão","Moda","Mediana","Contagem"]'::jsonb, 0, 'Desvio padrão resume o quanto os valores se afastam da MÉDIA.', null, true, 37, 'question_bank_reset_v1', 2, 'conceitual', array['estatistica','desvio_padrao'], 60),
  ('diagnostico_v1_038', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Correlação com cuidado', 'Você encontrou correlação alta entre visitas e vendas. Qual conclusão é mais adequada?', '', 'Análise de duas métricas.', '["Prova causalidade direta","Indica associação e exige investigação de causa","Significa que uma variável é inútil","Dispensa análise de contexto"]'::jsonb, 1, 'Correlação sinaliza associação, não comprova causa por si só.', null, true, 38, 'question_bank_reset_v1', 3, 'interpretacao', array['estatistica','correlacao','causalidade'], 75),
  ('diagnostico_v1_039', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Taxa ponderada', 'Uma loja pequena converte 80% em 10 leads e outra 40% em 100 leads. Como comparar sem distorção?', '', 'Volumes diferentes entre lojas.', '["Tirar MÉDIA simples das taxas","Calcular taxa global ponderada pelo volume","Olhar apenas a maior taxa","Comparar apenas o número de lojas"]'::jsonb, 1, 'Taxa ponderada respeita diferentes volumes de observações.', null, true, 39, 'question_bank_reset_v1', 3, 'cenario', array['estatistica','ponderacao','taxa'], 75),
  ('diagnostico_v1_040', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Sazonalidade', 'As vendas de dezembro são sempre altas. Qual cuidado evita interpretar dezembro como ganho estrutural permanente?', '', 'Série mensal com padrão sazonal.', '["Comparar com novembro apenas","Comparar com dezembro de anos anteriores e controlar sazonalidade","Ignorar histórico","Usar MÉDIA de uma semana"]'::jsonb, 1, 'Comparação com período equivalente reduz viés sazonal.', null, true, 40, 'question_bank_reset_v1', 3, 'negocio', array['estatistica','sazonalidade','serie_temporal'], 75),
  ('diagnostico_v1_041', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Intervalo de confiança', 'Ao reportar uma taxa estimada em pesquisa, o que o intervalo de confiança comunica?', '', 'Pesquisa de satisfação com amostra.', '["Faixa plausível para o parâmetro populacional","Valor exato sem incerteza","Número de respostas invalidadas","Apenas erro de digitação"]'::jsonb, 0, 'Intervalo expressa incerteza da estimativa com base na amostra.', null, true, 41, 'question_bank_reset_v1', 4, 'conceitual', array['estatistica','intervalo_confianca'], 90),
  ('diagnostico_v1_042', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Teste A B básico', 'No teste A/B, a variação B teve taxa maior, mas com poucas observações. Qual passo vem antes de escalar para toda base?', '', 'Experimento digital com baixa amostra.', '["Escalar imediatamente","Verificar significância estatística e tamanho de efeito","Escolher pela opinião do time","Ignorar variância"]'::jsonb, 1, 'Decisão robusta combina significância, efeito e contexto de negócio.', null, true, 42, 'question_bank_reset_v1', 4, 'cenario', array['estatistica','teste_ab','significancia'], 90),
  ('diagnostico_v1_043', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Distribuição assimétrica', 'Uma métrica de ticket possui cauda longa. Qual resumo costuma ser mais robusto para benchmark operacional?', '', 'Distribuição com poucos valores muito altos.', '["Média simples","Mediana e percentis","Soma total","Valor MÁXIMO"]'::jsonb, 1, 'Mediana e percentis descrevem melhor distribuições assimétricas.', null, true, 43, 'question_bank_reset_v1', 3, 'interpretacao', array['estatistica','percentil','mediana'], 75),
  ('diagnostico_v1_044', 'diagnostico', 'Estatística', 'Estatística', 'Intermediário', 'Risco de viés', 'Uma pesquisa interna foi respondida apenas por usuários muito engajados. Qual risco metodológico aparece aqui?', '', 'Baixa representatividade da amostra.', '["Viés de seleção","Erro de arredondamento","Overfitting de modelo","saturação de índice"]'::jsonb, 0, 'Quando um grupo domina respostas, a amostra pode não representar a população.', null, true, 44, 'question_bank_reset_v1', 3, 'negocio', array['estatistica','vies_selecao'], 75),
  ('diagnostico_v1_045', 'diagnostico', 'Estatística', 'Estatística', 'Avançado', 'Controle de variáveis', 'Conversão subiu após nova campanha, mas também houve desconto no mesmo período. Qual abordagem ajuda a separar efeitos?', '', 'Mudança simultânea de alavancas.', '["Comparar apenas MÉDIA antes e depois","Controlar variáveis relevantes em modelo apropriado","Ignorar período de desconto","Usar apenas opinião comercial"]'::jsonb, 1, 'Controlar variáveis reduz atribuição incorreta de efeito.', null, true, 45, 'question_bank_reset_v1', 5, 'negocio', array['estatistica','causalidade','controle'], 90),
  ('diagnostico_v1_046', 'diagnostico', 'Estatística', 'Estatística', 'Avançado', 'Detecção de anomalia', 'Uma série de pedidos apresenta pico atípico em um dia. Qual fluxo analítico é mais adequado?', '', 'Possível fraude ou evento real.', '["Descartar automaticamente o ponto","Investigar causa raiz e comparar com bandas históricas","Trocar todos valores por MÉDIA","Parar a coleta"]'::jsonb, 1, 'Anomalias devem ser investigadas antes de qualquer tratamento definitivo.', null, true, 46, 'question_bank_reset_v1', 4, 'cenario', array['estatistica','anomalia','serie_temporal'], 90),
  ('diagnostico_v1_047', 'diagnostico', 'Estatística', 'Estatística', 'Avançado', 'Métrica de erro', 'Você esta comparando modelos de previsao de demanda com diferentes escalas de produto. Qual métrica favorece comparação relativa?', '', 'Produtos com volumes muito diferentes.', '["MAE absoluto sem contexto","MAPE ou outra métrica relativa","Soma do erro bruto","Contagem de registros"]'::jsonb, 1, 'Métricas relativas ajudam a comparar desempenho entre escalas diferentes.', null, true, 47, 'question_bank_reset_v1', 5, 'interpretacao', array['estatistica','forecast','erro_relativo'], 90),
  ('diagnostico_v1_048', 'diagnostico', 'Estatística', 'Estatística', 'Avançado', 'Drift de dados', 'Um modelo antes estável piorou gradualmente nos últimos meses. Qual hipotese deve ser testada primeiro?', '', 'Mudança de comportamento dos dados de entrada.', '["Drift de distribuição das variáveis","Falha de internet do analista","Troca de cor do dashboard","Tamanho da fonte da tela"]'::jsonb, 0, 'Mudança de distribuição entre treino e produção afeta desempenho do modelo.', null, true, 48, 'question_bank_reset_v1', 5, 'negocio', array['estatistica','modelagem','drift'], 90),
  ('diagnostico_v1_049', 'diagnostico', 'Indicadores', 'Indicadores', 'Básico', 'Meta e realizado', 'Um time bateu 92 de uma meta de 100. Qual leitura está correta?', '', 'KPI mensal de execução.', '["Atingimento de 92% com gap de -8","Atingimento de 108% com gap de +8","Atingimento de 8% com gap de -92","Não é possível calcular"]'::jsonb, 0, 'Atingimento é realizado dividido pela meta; gap absoluto é realizado menos meta.', null, true, 49, 'question_bank_reset_v1', 1, 'conceitual', array['kpi','meta','gap'], 45),
  ('diagnostico_v1_050', 'diagnostico', 'Indicadores', 'Indicadores', 'Básico', 'KPI acionável', 'Qual indicador é mais útil para agir sobre perda em funil comercial?', '', 'Funil com várias etapas.', '["Taxa de conversão por etapa","Taxa de clique no CTA da página","Tempo médio entre etapas do funil","Percentual de leads qualificados por canal"]'::jsonb, 0, 'Taxa por etapa mostra onde ocorre a maior perda e orienta ação.', null, true, 50, 'question_bank_reset_v1', 2, 'negocio', array['kpi','funil','conversao'], 60),
  ('diagnostico_v1_051', 'diagnostico', 'Indicadores', 'Indicadores', 'Básico', 'Definição consistente', 'Dois times calculam churn com fórmulas diferentes. Qual prática evita conflito de número oficial?', '', 'Falta de padrão de definição.', '["Documentar definição oficial e regra de cálculo","Escolher sempre o menor valor","Usar MÉDIA das duas contas","Trocar o nome da métrica"]'::jsonb, 0, 'Governança de métricas exige definição única e documentada.', null, true, 51, 'question_bank_reset_v1', 2, 'negocio', array['kpi','governanca','definicao'], 60),
  ('diagnostico_v1_052', 'diagnostico', 'Indicadores', 'Indicadores', 'Básico', 'Indicador absoluto vs relativo', 'Para comparar desempenho de lojas com tamanhos diferentes, qual métrica tende a ser mais justa?', '', 'Lojas com volumes distintos.', '["Receita total absoluta","Taxa normalizada por base comparável","Número de funcionarios","Ticket MÁXIMO da loja"]'::jsonb, 1, 'Taxas normalizadas facilitam comparação entre unidades de tamanho diferente.', null, true, 52, 'question_bank_reset_v1', 2, 'interpretacao', array['kpi','normalizacao'], 60),
  ('diagnostico_v1_053', 'diagnostico', 'Indicadores', 'Indicadores', 'Básico', 'Periodicidade', 'Um KPI operacional muda todo dia. Qual cadência de monitoramento costuma ser adequada?', '', 'Processo com alta variação diária.', '["Acompanhamento diário com consolidação semanal","Apenas anual","Somente quando houver crise","Nunca revisar"]'::jsonb, 0, 'Cadência deve refletir velocidade de mudança e capacidade de resposta.', null, true, 53, 'question_bank_reset_v1', 1, 'negocio', array['kpi','monitoramento','cadencia'], 45),
  ('diagnostico_v1_054', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Decomposicao de KPI', 'A margem caiu no trimestre. Qual análise inicial aumenta chance de achar causa raiz?', '', 'Margem depende de preço, custo e mix.', '["Quebrar por preço, custo e mix por segmento","Olhar apenas MÉDIA geral","Trocar meta do trimestre","Ignorar histórico"]'::jsonb, 0, 'Decompor componentes evita conclusões superficiais sobre o indicador.', null, true, 54, 'question_bank_reset_v1', 3, 'cenario', array['kpi','margem','decomposicao'], 75),
  ('diagnostico_v1_055', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Leading vs lagging', 'Qual exemplo representa melhor um indicador leading para receita futura?', '', 'Time quer antecipar queda de faturamento.', '["Taxa de conversão de proposta em andamento","Receita fechada do mês passado","Lucro contábil já auditado","DRE anual fechada"]'::jsonb, 0, 'Leading indicator antecede o resultado final e ajuda ação preventiva.', null, true, 55, 'question_bank_reset_v1', 3, 'conceitual', array['kpi','leading_indicator'], 75),
  ('diagnostico_v1_056', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Meta por segmento', 'Uma meta única penaliza unidades com perfis muito diferentes. Qual alternativa melhora equidade?', '', 'Unidades com maturidade distinta.', '["Definir metas segmentadas por contexto comparável","Aplicar mesma meta para todos sem ajuste","Retirar todas metas","Comparar apenas unidade campea"]'::jsonb, 0, 'Metas segmentadas preservam comparabilidade e realismo operacional.', null, true, 56, 'question_bank_reset_v1', 3, 'negocio', array['kpi','metas','segmentacao'], 75),
  ('diagnostico_v1_057', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Efeito composicao', 'Ticket médio subiu, mas receita total caiu. Qual verificação evita Interpretação errada?', '', 'Mudança simultânea de volume e ticket.', '["Analisar também volume de pedidos e mix de clientes","Concluir que tudo melhorou","Usar só o ticket médio","Ignorar variação de base"]'::jsonb, 0, 'Indicadores devem ser lidos em conjunto para evitar efeito composicao.', null, true, 57, 'question_bank_reset_v1', 3, 'interpretacao', array['kpi','ticket_medio','volume'], 75),
  ('diagnostico_v1_058', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Benchmark interno', 'Para comparar filiais, qual critério de benchmark reduz viés de contexto?', '', 'Filiais em regiões com realidades distintas.', '["Comparar filiais por clusters semelhantes","Comparar sempre contra a maior filial","Usar apenas ranking bruto","Escolher filial aleatoria"]'::jsonb, 0, 'Benchmark por pares comparáveis torna conclusão mais justa.', null, true, 58, 'question_bank_reset_v1', 3, 'negocio', array['kpi','benchmark','clusters'], 75),
  ('diagnostico_v1_059', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'KPI de qualidade', 'O volume de atendimentos aumentou, mas reclamacoes também. Qual painel apoia decisão melhor?', '', 'Operação de suporte ao cliente.', '["Volume, tempo médio e taxa de reabertura juntos","Somente volume de atendimentos","Apenas total de horas do time","Número de cadeiras no escritorio"]'::jsonb, 0, 'Combinar produtividade e qualidade evita incentivo a comportamento distorcido.', null, true, 59, 'question_bank_reset_v1', 4, 'cenario', array['kpi','qualidade','suporte'], 90),
  ('diagnostico_v1_060', 'diagnostico', 'Indicadores', 'Indicadores', 'Intermediário', 'Sinal versus ruido', 'Um KPI oscilou muito em poucos dias. Qual prática ajuda a evitar reação exagerada?', '', 'Série diária com ruido alto.', '["Observar tendência em janela movel e contexto operacional","Mudar estratégia a cada dia","Ignorar totalmente os dados","Usar apenas um ponto isolado"]'::jsonb, 0, 'Suavizacao e contexto reduzem decisões baseadas em ruido de curto prazo.', null, true, 60, 'question_bank_reset_v1', 3, 'interpretacao', array['kpi','janela_movel','ruido'], 75),
  ('diagnostico_v1_061', 'diagnostico', 'Indicadores', 'Indicadores', 'Avançado', 'Árvore de métricas', 'Para explicar variação de lucro para diretoria, qual abordagem melhora transparência causal?', '', 'Lucro depende de receita, custo e despesas.', '["Construir Árvore de métricas com contribuição de cada driver","Mostrar apenas lucro final","Remover detalhes de custo","Comparar somente com ano passado"]'::jsonb, 0, 'Árvore de métricas torna explícita a contribuição de cada componente.', null, true, 61, 'question_bank_reset_v1', 5, 'negocio', array['kpi','drivers','lucro'], 90),
  ('diagnostico_v1_062', 'diagnostico', 'Indicadores', 'Indicadores', 'Avançado', 'Meta dinâmica', 'Mercado sofreu choque externo e a meta original ficou inviável. Qual ajuste preserva governança?', '', 'Mudança de contexto macroeconômico.', '["Revisar meta com critério documentado e trilha de aprovação","Alterar meta sem registro","Manter meta inviável para pressionar time","Excluir indicador"]'::jsonb, 0, 'Revisão formal de meta protege comparabilidade e accountability.', null, true, 62, 'question_bank_reset_v1', 4, 'negocio', array['kpi','governanca','meta_dinamica'], 90),
  ('diagnostico_v1_063', 'diagnostico', 'Indicadores', 'Indicadores', 'Avançado', 'Métrica norte', 'Um produto digital quer alinhar squads em um objetivo comum de crescimento sustentável. Qual escolha é mais adequada?', '', 'Times com metas conflitantes.', '["Definir métrica norte ligada a valor de usuário e receita","Atribuir metas desconectadas por equipe","Usar apenas métrica de vaidade","Trocar métrica toda semana"]'::jsonb, 0, 'A métrica north star conecta times ao mesmo valor de negócio.', null, true, 63, 'question_bank_reset_v1', 5, 'negocio', array['kpi','north_star','produto'], 90),
  ('diagnostico_v1_064', 'diagnostico', 'Indicadores', 'Indicadores', 'Avançado', 'Diagnóstico multicausal', 'NPS caiu e churn subiu no mesmo trimestre. Qual plano de análise é mais robusto?', '', 'múltiplos sinais negativos simultaneos.', '["Cruzar jornadas, tempo de resposta e cohorts de cancelamento","Olhar apenas MÉDIA global de NPS","Mudar pesquisa de escala sem análise","Ignorar churn no período"]'::jsonb, 0, 'Combinar sinais de experiencia e comportamento amplia chance de causa raiz.', null, true, 64, 'question_bank_reset_v1', 5, 'cenario', array['kpi','nps','churn'], 90),
  ('diagnostico_v1_065', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Básico', 'Granularidade', 'Uma base tem uma linha por item. O gestor quer número de pedidos. Qual cuidado e essencial?', '', 'Pedido_id repete por item.', '["Contar pedidos distintos","Contar linhas da tabela","Somar ids","Ordenar por nome do item"]'::jsonb, 0, 'Granularidade por item exige DISTINCT para contar pedidos.', null, true, 65, 'question_bank_reset_v1', 2, 'cenario', array['logica_dados','granularidade','distinct'], 60),
  ('diagnostico_v1_066', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Básico', 'Tipo numérico', 'A coluna valor chegou como texto e a SOMA não funciona. Qual ação resolve a causa do problema?', '', 'Importação com tipo incorreto.', '["Converter a coluna para numérico","Aplicar arredondamento antes de corrigir o tipo","Remover separador de milhar sem validar decimal","Trocar apenas o formato da célula para Número"]'::jsonb, 0, 'Operações matemáticas exigem tipo numérico válido.', null, true, 66, 'question_bank_reset_v1', 1, 'conceitual', array['logica_dados','tipo_dado','numerico'], 45),
  ('diagnostico_v1_067', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Básico', 'Chave primária', 'Em um cadastro de clientes, qual campo deveria ter unicidade para evitar duplicatas diretas?', '', 'Base de clientes com atualizações frequentes.', '["Identificador de cliente","Cidade","Nome fantasia","Canal de venda"]'::jsonb, 0, 'Chave primária única reduz ambiguidade de identificação.', null, true, 67, 'question_bank_reset_v1', 1, 'conceitual', array['logica_dados','chave_primaria'], 45),
  ('diagnostico_v1_068', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Básico', 'Data de referência', 'Dois relatórios do mesmo KPI divergiram porque usaram datas diferentes de fechamento. Qual prática evita esse erro?', '', 'Times diferentes publicam o mesmo indicador.', '["Padronizar data de corte e regra de fechamento","Escolher a data mais antiga","Comparar apenas quando coincidir","Remover coluna de data"]'::jsonb, 0, 'Regra de data de corte deve ser única para comparabilidade.', null, true, 68, 'question_bank_reset_v1', 2, 'negocio', array['logica_dados','data_corte','governanca'], 60),
  ('diagnostico_v1_069', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Básico', 'Consistência de categoria', 'Uma coluna de categoria tem valores como Sul, sul e SUL. Qual ação melhora a consistência para análise?', '', 'Dimensão de região com variações de escrita.', '["Padronizar texto com regra única de formatação","Manter como esta","Excluir a coluna","Criar uma categoria por variação"]'::jsonb, 0, 'Padronização reduz fragmentação e erro em agrupamentos.', null, true, 69, 'question_bank_reset_v1', 2, 'cenario', array['logica_dados','padronizacao','categoria'], 60),
  ('diagnostico_v1_070', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Modelo fato dimensão', 'Por que separar tabela fato e dimensão facilita análise?', '', 'Modelo analítico para BI.', '["Organiza medidas e contexto com menor redundância","Impede filtros por categoria","Elimina necessidade de chaves","Substitui validação de dados"]'::jsonb, 0, 'Separação entre eventos e atributos melhora flexibilidade e consistência.', null, true, 70, 'question_bank_reset_v1', 3, 'conceitual', array['logica_dados','modelagem','fato_dimensao'], 75),
  ('diagnostico_v1_071', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Conformidade de dimensão', 'Uma empresa tem duas tabelas de produto com códigos diferentes por canal. Qual risco principal surge sem dimensão conformada?', '', 'múltiplos sistemas de origem.', '["Comparação inconsistente entre canais","Aumento automático de desempenho","Eliminação de duplicatas","Redução de volume de dados"]'::jsonb, 0, 'Sem dimensão conformada, indicadores podem não ser comparáveis.', null, true, 71, 'question_bank_reset_v1', 3, 'negocio', array['logica_dados','dimensao_conformada'], 75),
  ('diagnostico_v1_072', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Linha do tempo de status', 'Você precisa saber em qual etapa cada chamado permaneceu mais tempo. Qual estrutura de dado ajuda mais?', '', 'Histórico de mudanças de status com timestamps.', '["Tabela de eventos com início e fim por status","Somente status atual","Apenas total de chamados","Lista sem data"]'::jsonb, 0, 'Histórico temporal permite medir tempo por etapa do processo.', null, true, 72, 'question_bank_reset_v1', 3, 'cenario', array['logica_dados','eventos','tempo_etapa'], 75),
  ('diagnostico_v1_073', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Nulo semantico', 'Em uma coluna de desconto, nulo pode significar sem desconto ou dado ausente. Qual abordagem é mais segura?', '', 'Interpretação de nulos afeta KPI.', '["Definir semântica de nulo e tratar explicitamente","Assumir sempre zero sem documentar","Remover coluna","Substituir por texto aleatorio"]'::jsonb, 0, 'Semântica documentada evita viés e interpretações erradas.', null, true, 73, 'question_bank_reset_v1', 3, 'negocio', array['logica_dados','nulos','semantica'], 75),
  ('diagnostico_v1_074', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Slowly changing context', 'O limite de crédito de cliente muda ao longo do tempo. Como manter histórico para análise correta de decisões passadas?', '', 'Análise requer contexto da época.', '["Sobrescrever sempre o valor antigo","Manter histórico versionado com vigência","Salvar apenas último valor","Excluir registros antigos"]'::jsonb, 1, 'Versionamento temporal preserva contexto histórico das análises.', null, true, 74, 'question_bank_reset_v1', 4, 'cenario', array['logica_dados','historico','vigencia'], 90),
  ('diagnostico_v1_075', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Regra de negócio centralizada', 'Cada analista calcula cliente ativo com critério diferente. Qual solução reduz divergência recorrente?', '', 'Falta de padrão entre squads.', '["Criar camada semântica com regra oficial reutilizável","Deixar cada um escolher seu critério","Comparar apenas planilhas finais","Trocar o nome da métrica"]'::jsonb, 0, 'Camada semântica centraliza regra e reduz inconsistências.', null, true, 75, 'question_bank_reset_v1', 4, 'negocio', array['logica_dados','camada_semantica','governanca'], 90),
  ('diagnostico_v1_076', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Intermediário', 'Integridade referencial', 'Pedidos estão chegando com cliente_id inexistente na dimensão clientes. Qual alerta isso indica?', '', 'Falha em validação de carga.', '["Quebra de integridade referencial","Melhora de desempenho","Erro de ordenação visual","Necessidade de mais colunas"]'::jsonb, 0, 'Chave estrangeira sem correspondência indica problema de qualidade/integração.', null, true, 76, 'question_bank_reset_v1', 3, 'interpretacao', array['logica_dados','integridade_referencial'], 75),
  ('diagnostico_v1_077', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Avançado', 'Data contract', 'Times de engenharia e analytics discutem schema a cada deploy. Qual prática reduz quebra inesperada?', '', 'Pipeline com múltiplos consumidores.', '["Adotar contrato de dados versionado com validação automática","Alterar schema sem aviso","Depender de comunicação informal","Remover testes de carga"]'::jsonb, 0, 'Data contracts formalizam expectativas e previnem quebras silenciosas.', null, true, 77, 'question_bank_reset_v1', 5, 'negocio', array['logica_dados','data_contract','pipeline'], 90),
  ('diagnostico_v1_078', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Avançado', 'Linhagem de dados', 'Um número de faturamento ficou diferente no comitê executivo. Qual artefato ajuda a rastrear onde a divergência nasceu?', '', 'Há várias camadas até o dashboard final.', '["Mapa de linhagem de dados de ponta a ponta","Histórico de atualização das tabelas fonte","Registro de regras de transformação aplicadas","Conciliação por chave entre camadas do pipeline"]'::jsonb, 0, 'A linhagem explícita a origem e as transformações até o indicador final.', null, true, 78, 'question_bank_reset_v1', 4, 'interpretacao', array['logica_dados','linhagem','governanca'], 90),
  ('diagnostico_v1_079', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Avançado', 'Reconciliação financeira', 'Dois sistemas reportam receita diferente para o mesmo dia. Qual procedimento técnico é mais robusto?', '', 'ERP e plataforma comercial divergindo.', '["Conciliar por chave de transação e regras de arredondamento","Usar sempre o maior valor","Ignorar diferenças pequenas","Comparar apenas totais mensais"]'::jsonb, 0, 'Reconciliação por transação identifica origem da divergência com precisão.', null, true, 79, 'question_bank_reset_v1', 5, 'cenario', array['logica_dados','reconciliacao','financeiro'], 90),
  ('diagnostico_v1_080', 'diagnostico', 'Lógica de dados', 'Lógica de dados', 'Avançado', 'Observabilidade de dados', 'Falhas de carga são percebidas apenas quando o dashboard quebra. Qual evolução reduz tempo de detecção?', '', 'ausência de monitoramento proativo.', '["Monitorar frescor, volume e qualidade com alertas automáticos","Aguardar reclamação do usuário","Atualizar dashboard manualmente","Excluir histórico de erros"]'::jsonb, 0, 'Observabilidade detecta anomalias cedo e reduz impacto operacional.', null, true, 80, 'question_bank_reset_v1', 5, 'negocio', array['logica_dados','observabilidade','qualidade'], 90),
  ('desafio_v1_001', 'desafio', 'SQL prático', 'SQL prático', 'Básico', 'Filtro em data', 'Você recebeu um chamado para auditar pedidos recentes. Qual consulta retorna somente pedidos dos últimos 7 dias?', 'Select * from pedidos ...', 'Tabela pedidos com coluna data_pedido.', '["WHERE data_pedido >= data atual menos 7 dias","WHERE data_pedido entre início do mês e hoje","WHERE data_pedido <= data atual menos 7 dias","HAVING COUNT(*) > 0"]'::jsonb, 0, 'A restrição temporal deve entrar no WHERE para limitar as linhas.', 10, true, 1, 'question_bank_reset_v1', 2, 'codigo', array['desafio','sql','where','data'], 60),
  ('desafio_v1_002', 'desafio', 'SQL prático', 'SQL prático', 'Intermediário', 'Contagem única', 'Você quer contar clientes distintos que compraram no mês. Qual expressão está correta?', '', 'Tabela vendas possui cliente_id repetido.', '["COUNT(cliente_id)","COUNT(*)","COUNT(DISTINCT cliente_id)","SUM(cliente_id)"]'::jsonb, 2, 'COUNT(DISTINCT) remove repetições de cliente_id.', 15, true, 2, 'question_bank_reset_v1', 3, 'cenario', array['desafio','sql','distinct'], 75),
  ('desafio_v1_003', 'desafio', 'SQL prático', 'SQL prático', 'Intermediário', 'JOIN correto', 'Qual JOIN preserva todos os produtos, mesmo sem venda no período?', '', 'Produtos sem correspondência em vendas.', '["INNER JOIN","LEFT JOIN partindo de produtos","RIGHT JOIN partindo de vendas","CROSS JOIN"]'::jsonb, 1, 'LEFT JOIN com produtos na esquerda preserva o cadastro completo.', 15, true, 3, 'question_bank_reset_v1', 3, 'conceitual', array['desafio','sql','left_join'], 75),
  ('desafio_v1_004', 'desafio', 'SQL prático', 'SQL prático', 'Avançado', 'Ranking por cliente', 'Qual solução encontra a maior compra por cliente sem perder detalhes das demais linhas?', 'Row_number() over (...)', 'Tabela compras com cliente_id e valor.', '["GROUP BY cliente e pegar MAX(valor) sem detalhes","ROW_NUMBER() OVER(PARTITION BY cliente_id ORDER BY valor DESC)","DISTINCT em valor","ORDER BY global por valor"]'::jsonb, 1, 'ROW_NUMBER por partição permite identificar topo mantendo granularidade.', 20, true, 4, 'question_bank_reset_v1', 4, 'codigo', array['desafio','sql','window_function'], 90),
  ('desafio_v1_005', 'desafio', 'Excel/BI', 'Excel/BI', 'Básico', 'Procura por chave', 'Em uma planilha de atendimento, você digitou o código do cliente e precisa retornar automaticamente o nome. Qual função resolve isso?', '', 'Planilha de apoio com código e nome.', '["SOMA","PROCV ou PROCX","CONT.SE","MAX"]'::jsonb, 1, 'PROCV/PROCX fazem busca por chave em tabela de referência.', 10, true, 5, 'question_bank_reset_v1', 2, 'cenario', array['desafio','excel','procx'], 60),
  ('desafio_v1_006', 'desafio', 'Excel/BI', 'Excel/BI', 'Intermediário', 'Tabela dinâmica', 'Em uma tabela dinâmica, onde deve ficar a medida de receita?', '', 'Análise por mês e categoria.', '["Em Linhas como texto","Em Valores com agregação","Em Filtros com MÉDIA de receita","Em Colunas com faixas de receita sem agregação"]'::jsonb, 1, 'Medidas numéricas devem ir em Valores para agregação correta.', 15, true, 6, 'question_bank_reset_v1', 3, 'conceitual', array['desafio','excel','tabela_dinamica'], 75),
  ('desafio_v1_007', 'desafio', 'Excel/BI', 'Excel/BI', 'Intermediário', 'Qualidade de chave', 'PROCX falha para alguns códigos que existem. Qual causa é mais provável?', '', 'Chaves com espaços invisiveis.', '["Espaços ou tipo de dado diferente na chave","Diferença de maiúsculas e minúsculas entre as chaves","Intervalo de busca não inclui todas as linhas","Tipo de correspondência incorreto na fórmula de busca"]'::jsonb, 0, 'Inconsistência de chave e causa comum de não correspondência.', 15, true, 7, 'question_bank_reset_v1', 3, 'interpretacao', array['desafio','excel','qualidade_dados'], 75),
  ('desafio_v1_008', 'desafio', 'Excel/BI', 'Excel/BI', 'Avançado', 'Modelo analítico', 'Qual benefício principal de usar modelo de dados em vez de juntar tudo em uma única aba?', '', 'Tabelas de fatos e dimensões relacionadas.', '["Melhorar consistência e reduzir redundância","Eliminar qualquer necessidade de chave","Garantir zero erro humano","Impedir filtros cruzados"]'::jsonb, 0, 'Modelagem relacional melhora manutenção e coerência dos indicadores.', 20, true, 8, 'question_bank_reset_v1', 4, 'negocio', array['desafio','bi','modelagem'], 90),
  ('desafio_v1_009', 'desafio', 'Indicadores', 'Indicadores', 'Básico', 'Gap de meta', 'Meta de NPS era 70 e resultado foi 64. Qual gap absoluto?', '', 'Cálculo de diferença absoluta.', '["+6","-6","64%","70%"]'::jsonb, 1, 'Gap absoluto e resultado menos meta: 64 - 70 = -6.', 10, true, 9, 'question_bank_reset_v1', 2, 'conceitual', array['desafio','kpi','gap'], 60),
  ('desafio_v1_010', 'desafio', 'Indicadores', 'Indicadores', 'Intermediário', 'Leitura de funil', 'Qual métrica mostra melhor onde o funil comercial está perdendo mais oportunidades?', '', 'Funil com etapas definidas.', '["Receita total do trimestre","Taxa de conversão por etapa","Tempo médio de avanço entre etapas","Total de leads em cada etapa"]'::jsonb, 1, 'Taxa por etapa evidencia gargalo operacional no funil.', 15, true, 10, 'question_bank_reset_v1', 3, 'cenario', array['desafio','kpi','funil'], 75),
  ('desafio_v1_011', 'desafio', 'Indicadores', 'Indicadores', 'Intermediário', 'Interpretação combinada', 'O ticket médio subiu, mas a receita caiu. Qual fator deve ser checado primeiro?', '', 'Mudança simultânea de volume e valor.', '["Volume de pedidos e mix","Participação de categorias no período","Mudança no perfil de clientes atendidos","Variação do investimento comercial"]'::jsonb, 0, 'Receita depende de ticket e volume; avaliar apenas um componente distorce conclusão.', 15, true, 11, 'question_bank_reset_v1', 3, 'interpretacao', array['desafio','kpi','ticket_medio'], 75),
  ('desafio_v1_012', 'desafio', 'Indicadores', 'Indicadores', 'Avançado', 'North star', 'Qual escolha melhor caracteriza uma métrica norte de produto?', '', 'Produto busca crescimento com retenção.', '["Métrica conectada a valor contínuo para usuário","Métrica de vaidade sem impacto de negócio","Qualquer número que suba rápido","Métrica trocada a cada semana"]'::jsonb, 0, 'North star precisa refletir valor sustentável para usuário e negócio.', 20, true, 12, 'question_bank_reset_v1', 4, 'negocio', array['desafio','kpi','north_star'], 90),
  ('desafio_v1_013', 'desafio', 'Estatística', 'Estatística', 'Básico', 'Medida robusta', 'Em um painel com poucos pedidos muito altos e muitos pedidos médios, qual medida tende a representar melhor o centro dos dados?', '', 'Distribuição assimétrica.', '["Média","Mediana","Soma","Máximo"]'::jsonb, 1, 'Mediana reduz influência de valores extremos.', 10, true, 13, 'question_bank_reset_v1', 2, 'conceitual', array['desafio','estatistica','mediana'], 60),
  ('desafio_v1_014', 'desafio', 'Estatística', 'Estatística', 'Intermediário', 'Correlação', 'O que uma correlação alta entre duas variáveis indica?', '', 'Análise de associação.', '["Existe causalidade comprovada","Há associação e precisa de investigação adicional","As variáveis são idênticas","Uma variável deve ser removida"]'::jsonb, 1, 'Correlação não comprova causa; apenas sinaliza relação estatística.', 15, true, 14, 'question_bank_reset_v1', 3, 'interpretacao', array['desafio','estatistica','correlacao'], 75),
  ('desafio_v1_015', 'desafio', 'Estatística', 'Estatística', 'Intermediário', 'Amostra enviesada', 'Uma pesquisa foi respondida apenas por clientes premium. Qual risco aparece?', '', 'Objetivo era representar toda base.', '["Viés de seleção","Erro de arredondamento","Falta de ordenação","Excesso de colunas"]'::jsonb, 0, 'Amostra não representativa pode enviesar conclusões.', 15, true, 15, 'question_bank_reset_v1', 3, 'negocio', array['desafio','estatistica','vies'], 75),
  ('desafio_v1_016', 'desafio', 'Estatística', 'Estatística', 'Avançado', 'Teste A B', 'No teste A/B, qual critério é mais adequado antes de escalar a variante?', '', 'Variante B parece melhor com amostra pequena.', '["Mudança absoluta na taxa sem intervalo de confiança","Significância estatística e tamanho de efeito","Custo incremental por conversão esperada","Risco de regressão por segmento de usuário"]'::jsonb, 1, 'Decisão deve considerar confiança estatística e impacto prático.', 20, true, 16, 'question_bank_reset_v1', 4, 'cenario', array['desafio','estatistica','teste_ab'], 90),
  ('desafio_v1_017', 'desafio', 'Lógica analítica', 'Lógica analítica', 'Básico', 'Granularidade', 'Se a base possui uma linha por item vendido, como contar pedidos corretamente?', '', 'Pedido_id se repete por item.', '["COUNT(*)","COUNT(DISTINCT pedido_id)","COUNT(pedido_id)","SUM(valor_total)"]'::jsonb, 1, 'Com granularidade por item, DISTINCT evita supercontagem de pedidos.', 10, true, 17, 'question_bank_reset_v1', 2, 'cenario', array['desafio','logica','granularidade'], 60),
  ('desafio_v1_018', 'desafio', 'Lógica analítica', 'Lógica analítica', 'Intermediário', 'Integridade de chave', 'Pedidos com cliente_id inexistente na dimensão clientes sugerem qual problema?', '', 'Carga com inconsistências entre tabelas.', '["Quebra de integridade referencial","Melhora de desempenho","Aumento de conversão","Erro apenas visual"]'::jsonb, 0, 'Falta de correspondência de chave indica problema de integridade.', 15, true, 18, 'question_bank_reset_v1', 3, 'interpretacao', array['desafio','logica','integridade'], 75),
  ('desafio_v1_019', 'desafio', 'Lógica analítica', 'Lógica analítica', 'Intermediário', 'Semântica de nulos', 'Na coluna desconto, nulo pode significar ausência de dado ou sem desconto. Qual ação evita erro de KPI?', '', 'Regra de negócio não documentada.', '["Documentar semântica e tratar nulo explicitamente","Sempre converter nulo em zero sem critério","Excluir registros nulos","Ignorar coluna desconto"]'::jsonb, 0, 'Semântica clara de nulo evita viés no cálculo de indicadores.', 15, true, 19, 'question_bank_reset_v1', 3, 'negocio', array['desafio','logica','nulos'], 75),
  ('desafio_v1_020', 'desafio', 'Lógica analítica', 'Lógica analítica', 'Avançado', 'Linhagem', 'Quando um KPI diverge entre dois painéis, qual artefato ajuda mais a localizar a origem da diferença?', '', 'Existem várias etapas de transformação.', '["Mapa de linhagem de dados","Histórico de versões das transformações","Log de qualidade na etapa de carga","Conciliação entre fonte e métrica publicada"]'::jsonb, 0, 'Linhagem permite rastrear transformações e identificar ponto de divergência.', 20, true, 20, 'question_bank_reset_v1', 4, 'negocio', array['desafio','logica','linhagem'], 90)
on conflict (question_key) do nothing;

-- Validações pós-execução
select mode, count(*) as total
from public.question_bank
where is_active = true
group by mode
order by mode;

select mode, level, count(*) as total
from public.question_bank
where is_active = true
group by mode, level
order by mode, level;

select mode, area, count(*) as total
from public.question_bank
where is_active = true
group by mode, area
order by mode, area;

select mode, is_active, count(*) as total
from public.question_bank
group by mode, is_active
order by mode, is_active desc;

commit;








