-- Data Skill Map - schema base para coleta anonima
-- Execute no SQL Editor do Supabase.

create table if not exists public.diagnostic_sessions (
  id bigint generated by default as identity primary key,
  attempt_id text not null unique,
  anonymous_user_id text not null,
  finished_at timestamptz not null default now(),
  total_questions_answered integer not null default 0,
  total_correct integer not null default 0,
  total_wrong integer not null default 0,
  score_percent integer not null default 0,
  sql_level text,
  statistics_level text,
  data_level text,
  overall_level text,
  identified_profile text,
  study_recommendation text,
  priority_text text,
  stopped_at_level text,
  level_results jsonb not null default '[]'::jsonb,
  area_score_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnostic_answers (
  id bigint generated by default as identity primary key,
  attempt_id text not null,
  anonymous_user_id text not null,
  answered_at timestamptz not null default now(),
  order_index integer not null,
  area text not null,
  level text not null,
  concept text,
  question text not null,
  selected_answer text,
  correct_answer text,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_attempts (
  id bigint generated by default as identity primary key,
  attempt_id text not null,
  anonymous_user_id text not null,
  answered_at timestamptz not null default now(),
  challenge_index integer not null,
  challenge_theme text not null,
  challenge_level text not null,
  question text not null,
  selected_answer text,
  correct_answer text,
  is_correct boolean not null,
  points integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.diagnostic_sessions enable row level security;
alter table public.diagnostic_answers enable row level security;
alter table public.challenge_attempts enable row level security;

drop policy if exists "anon_insert_diagnostic_sessions" on public.diagnostic_sessions;
create policy "anon_insert_diagnostic_sessions"
on public.diagnostic_sessions
for insert
to anon
with check (true);

drop policy if exists "anon_insert_diagnostic_answers" on public.diagnostic_answers;
create policy "anon_insert_diagnostic_answers"
on public.diagnostic_answers
for insert
to anon
with check (true);

drop policy if exists "anon_insert_challenge_attempts" on public.challenge_attempts;
create policy "anon_insert_challenge_attempts"
on public.challenge_attempts
for insert
to anon
with check (true);

