-- Data Skill Map - Seed inicial de Diagnostic Recommendations
-- Execute docs/supabase-diagnostic-recommendations.sql antes deste arquivo.
-- Este seed e idempotente via recommendation_key.
-- O frontend ainda sera conectado a esta tabela em etapa futura.

insert into public.diagnostic_recommendations (
  recommendation_key,
  skill_code,
  area,
  level,
  concept,
  recommendation_type,
  severity,
  title,
  diagnosis_text,
  study_guidance,
  next_step,
  trigger_level,
  priority,
  is_active,
  source
)
values
  (
    'diag_rec_sql_filtering_where_logic_basic_review_v1',
    'sql.filtering.where_logic',
    'SQL',
    'Básico',
    'Filtros com WHERE',
    'review',
    'medium',
    'Reforce filtros antes da agregação',
    'Você demonstrou dificuldade em decidir quando uma condição deve filtrar linhas antes do cálculo. Esse erro costuma aparecer quando WHERE, GROUP BY e HAVING parecem fazer parte do mesmo passo.',
    'Revise a ordem lógica da consulta: FROM define a fonte, WHERE reduz as linhas, GROUP BY agrupa, HAVING filtra grupos e ORDER BY organiza o resultado final.',
    'Pratique três consultas simples filtrando datas, status e valores antes de qualquer agregação.',
    'Básico',
    80,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_sql_aggregation_counting_basic_review_v1',
    'sql.aggregation.counting',
    'SQL',
    'Básico',
    'Contagens e nulos',
    'review',
    'high',
    'Revise contagens com nulos e entidades',
    'Você demonstrou dificuldade em interpretar contagens. Isso costuma acontecer quando COUNT(*), COUNT(coluna) e contagem de entidades são tratados como equivalentes.',
    'Antes de calcular um indicador, defina se você quer contar linhas, valores preenchidos ou entidades únicas. Essa decisão muda o resultado e pode alterar completamente a leitura do negócio.',
    'Compare COUNT(*), COUNT(email) e COUNT(DISTINCT cliente_id) em uma mesma base com nulos e repetições.',
    'Básico',
    90,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_sql_group_filtering_intermediate_review_v1',
    'sql.aggregation.group_filtering',
    'SQL',
    'Intermediário',
    'Filtros em agregações',
    'review',
    'high',
    'Separe filtro de linha e filtro de grupo',
    'Você teve dificuldade em diferenciar WHERE de HAVING. Isso geralmente indica que a consulta ainda não está separando linhas individuais de resultados agregados.',
    'Use WHERE para retirar registros antes da soma, média ou contagem. Use HAVING somente quando a regra depende do valor já agregado, como lojas com faturamento acima de uma meta.',
    'Resolva um exercício com receita por loja filtrando cancelamentos no WHERE e metas de faturamento no HAVING.',
    'Intermediário',
    88,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_sql_join_granularity_intermediate_review_v1',
    'sql.join.granularity',
    'SQL',
    'Intermediário',
    'Granularidade de JOINs',
    'review',
    'critical',
    'Revise granularidade antes de avançar em JOINs',
    'Você demonstrou dificuldade em granularidade de JOINs. Isso costuma acontecer quando a consulta mistura pedidos e itens sem entender o nível da tabela.',
    'Antes de avançar para queries analíticas, revise cardinalidade 1:N, conte a chave de negócio antes e depois do JOIN e valide se a soma foi inflada por duplicidade.',
    'Monte uma consulta que compare pedidos, itens e receita antes e depois da junção, usando COUNT(DISTINCT pedido_id) como controle.',
    'Intermediário',
    100,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_excel_lookup_key_quality_intermediate_review_v1',
    'excel.lookup.key_quality',
    'Excel',
    'Intermediário',
    'Busca por chave',
    'review',
    'high',
    'Valide a chave antes de trocar a fórmula',
    'Você teve dificuldade em buscas por chave no Excel. Muitas vezes a fórmula está correta, mas a chave tem espaços invisíveis, tipos diferentes ou intervalo incompleto.',
    'Antes de substituir PROCV por PROCX ou recriar a planilha, confira tipo de dado, espaços extras, duplicidade da chave e cobertura do intervalo de busca.',
    'Crie uma aba de apoio com códigos limpos e teste quais chaves não encontram correspondência.',
    'Intermediário',
    92,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_excel_data_type_date_validation_basic_review_v1',
    'excel.data_type.date_validation',
    'Excel',
    'Básico',
    'Tipo de dado',
    'review',
    'high',
    'Corrija datas como dado, não só como formato',
    'Você demonstrou dificuldade com tipos de dados no Excel. Isso costuma aparecer quando uma data parece visualmente correta, mas ainda está armazenada como texto.',
    'Valide se datas, números e textos estão no tipo correto antes de criar gráficos, segmentações ou tabelas dinâmicas. Formatação visual não substitui conversão de tipo.',
    'Pegue uma coluna de datas em texto, converta para data real e confira se agrupamentos por mês funcionam corretamente.',
    'Básico',
    78,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_excel_pivot_analysis_layout_intermediate_review_v1',
    'excel.pivot.analysis_layout',
    'Excel',
    'Intermediário',
    'Tabela dinâmica',
    'review',
    'medium',
    'Organize dimensões e medidas na tabela dinâmica',
    'Você teve dificuldade em montar uma tabela dinâmica com leitura analítica. Isso costuma acontecer quando campos de dimensão e campos de medida são misturados.',
    'Use linhas e colunas para dimensões como mês, categoria ou canal. Use valores para medidas numéricas agregadas, como receita, quantidade ou margem.',
    'Monte uma tabela dinâmica com mês nas linhas, categoria nas colunas e soma da receita em valores.',
    'Intermediário',
    75,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_excel_data_quality_deduplication_intermediate_review_v1',
    'excel.data_quality.deduplication',
    'Excel',
    'Intermediário',
    'Duplicidade em base',
    'review',
    'high',
    'Deduplicate pela chave certa',
    'Você demonstrou dificuldade em tratar duplicidades sem distorcer indicadores. Remover linhas repetidas sem escolher uma chave de negócio pode apagar dados válidos ou manter duplicatas perigosas.',
    'Antes de remover duplicados, defina qual entidade deve ser única: pedido, cliente, item ou transação. A regra de deduplicação deve seguir essa entidade.',
    'Revise uma base de pedidos repetidos usando id_pedido como chave de controle e compare a soma antes e depois.',
    'Intermediário',
    82,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_stats_robust_measures_basic_review_v1',
    'stats.distribution.robust_measures',
    'Estatística',
    'Básico',
    'Medidas robustas',
    'review',
    'medium',
    'Use medidas robustas quando houver extremos',
    'Você demonstrou dificuldade em escolher uma medida de centro quando existem valores extremos. Nesses casos, a média pode contar uma história mais otimista ou mais pessimista do que a realidade típica.',
    'Compare média e mediana antes de concluir. Quando poucos valores muito altos ou muito baixos puxam a média, a mediana costuma representar melhor o comportamento central.',
    'Analise uma lista com outliers calculando média, mediana e amplitude, e escreva qual medida você usaria no relatório.',
    'Básico',
    74,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_stats_sampling_bias_intermediate_review_v1',
    'stats.sampling.bias',
    'Estatística',
    'Intermediário',
    'Viés de amostra',
    'review',
    'high',
    'Questione quem ficou fora da amostra',
    'Você demonstrou fragilidade ao avaliar representatividade da amostra. Isso pode levar a conclusões fortes com dados que representam apenas um recorte do público.',
    'Antes de interpretar percentuais, verifique quem respondeu, quem ficou fora, como a amostra foi selecionada e qual decisão será tomada com o resultado.',
    'Revise um cenário em que apenas clientes premium responderam e liste quais conclusões seriam arriscadas para toda a base.',
    'Intermediário',
    90,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_stats_correlation_vs_causation_intermediate_review_v1',
    'stats.relationship.correlation_vs_causation',
    'Estatística',
    'Intermediário',
    'Correlação e causalidade',
    'review',
    'high',
    'Não transforme correlação em causa sem investigar',
    'Você teve dificuldade em interpretar correlação. Uma associação alta entre duas variáveis é um sinal de investigação, não uma prova automática de causalidade.',
    'Procure hipóteses alternativas, variáveis de confusão e mudanças de contexto antes de propor uma ação. Correlação ajuda a perguntar melhor; não encerra a análise.',
    'Escolha duas métricas correlacionadas e escreva três explicações possíveis antes de sugerir uma decisão.',
    'Intermediário',
    86,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_kpi_target_interpretation_basic_review_v1',
    'kpi.target.interpretation',
    'Indicadores',
    'Básico',
    'Meta e resultado',
    'review',
    'medium',
    'Leia meta como diferença e contexto',
    'Você demonstrou dificuldade em interpretar meta e realizado. O erro mais comum é olhar apenas se o número subiu ou caiu, sem calcular o gap e sem olhar o contexto.',
    'Sempre separe resultado, meta, diferença absoluta e diferença percentual. Depois conecte a leitura ao período, segmento e regra de negócio.',
    'Calcule o gap absoluto e percentual de três indicadores e escreva uma frase de interpretação para cada um.',
    'Básico',
    70,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_kpi_funnel_conversion_intermediate_next_step_v1',
    'kpi.funnel.conversion_rate',
    'Indicadores',
    'Intermediário',
    'Funil de conversão',
    'next_step',
    'high',
    'Diagnostique o funil por etapa',
    'Você teve dificuldade em interpretar gargalos de funil. Olhar apenas o volume total pode esconder onde as oportunidades estão sendo perdidas.',
    'Compare taxa de conversão por etapa, volume absoluto e tempo médio de avanço. Um gargalo relevante combina perda proporcional com impacto real no volume final.',
    'Monte uma leitura com etapas do funil, destaque a maior queda e escreva uma recomendação operacional curta.',
    'Intermediário',
    88,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_data_logic_modeling_grain_basic_review_v1',
    'data_logic.modeling.grain',
    'Lógica de dados',
    'Básico',
    'Granularidade',
    'review',
    'critical',
    'Identifique o nível da tabela antes de contar',
    'Você demonstrou dificuldade em granularidade. Isso acontece quando uma tabela por item, pedido, cliente ou evento é analisada como se todas tivessem o mesmo nível.',
    'Antes de calcular qualquer indicador, responda: uma linha representa o quê? Depois escolha a chave correta para contar entidades, somar valores ou comparar períodos.',
    'Pegue uma base por item vendido e calcule quantidade de linhas, pedidos distintos e clientes distintos.',
    'Básico',
    98,
    true,
    'diagnostic_recommendations_seed_v1'
  ),
  (
    'diag_rec_data_logic_null_semantics_intermediate_review_v1',
    'data_logic.nulls.semantics',
    'Lógica de dados',
    'Intermediário',
    'Semântica de nulos',
    'review',
    'high',
    'Defina o que nulo significa antes de substituir por zero',
    'Você mostrou dificuldade com a semântica de valores nulos. Em dados reais, nulo pode significar ausência de informação, evento inexistente ou falha de integração.',
    'Tratar todo nulo como zero pode distorcer indicadores e esconder problemas de origem. Documente o significado do nulo por coluna antes de transformar o dado.',
    'Crie uma regra separando sem desconto, desconto desconhecido e registro incompleto antes de recalcular o KPI.',
    'Intermediário',
    90,
    true,
    'diagnostic_recommendations_seed_v1'
  )
on conflict (recommendation_key) do update
set
  skill_code = excluded.skill_code,
  area = excluded.area,
  level = excluded.level,
  concept = excluded.concept,
  recommendation_type = excluded.recommendation_type,
  severity = excluded.severity,
  title = excluded.title,
  diagnosis_text = excluded.diagnosis_text,
  study_guidance = excluded.study_guidance,
  next_step = excluded.next_step,
  trigger_level = excluded.trigger_level,
  priority = excluded.priority,
  is_active = excluded.is_active,
  source = excluded.source,
  updated_at = now();
