const state = {
  currentQuestion: 0,
  currentLevelIndex: 0,
  diagnosticStarted: false,
  diagnosticQuestionSets: [],
  selectedDiagnosticAnswer: null,
  diagnosticAnswers: [],
  levelResults: [],
  diagnosticStoppedAtLevel: null,
  resultRenderTimer: null,
  areaScore: {},
  challengeScore: 0,
  completedChallenges: new Set(),
  selectedChallengeOptions: {},
  anonymousUserId: null,
  currentDiagnosticAttemptId: null,
  heroPreviewIndex: 0,
  heroPreviewTimer: null,
  heroPreviewTransitioning: false
};
